### ISSUE TITLE
Export errors

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#17]
When exporting sites from the firefox addon, it produces a .mpsites file that cannot be imported into the iOS app. the iOS app says it doesn't look like a MasterPassword export.

using 2.0.0rc1

**Comment by ttyridal** [comment]
That's annoying. 

Does it fail with any of the other MasterPassword products? like the java version?

It does work for me (but I have very simple setup and relatively short sitenames etc), which leads me to think it's something with your .mpsites file. Or a particularity on ios (I don't have a device at hand).

(good timing by the way, I was just about to promote the RC1 as final release)

**Comment by ghost** [comment]
Actually, no. The java version seems to function fine. Wondering if @lhunath may be able to shed some light on this? using iOS version 2.1.88

**Comment by lhunath** [comment]
Can you attach an export file here?  Also, you may be able to find more details about the import failure in Master Password's log.

**Comment by ghost** [comment]
267-10:51:50          MPAppDelegate_Store.m:556 | ERROR   : Invalid header format in line: # Key ID:

Key ID is blank, not sure what its supposed to be.

Rather not post my own mpsites

**Comment by lhunath** [comment]
Java code trace for where the key ID comes from:
https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-model/src/main/java/com/lyndir/masterpassword/model/MPSiteMarshaller.java#L66
https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-model/src/main/java/com/lyndir/masterpassword/model/MPUser.java#L75
https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-algorithm/src/main/java/com/lyndir/masterpassword/MasterKey.java#L74
https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-algorithm/src/main/java/com/lyndir/masterpassword/MasterKeyV0.java#L144
https://github.com/Lyndir/MasterPassword/blob/master/MasterPassword/Java/masterpassword-algorithm/src/main/java/com/lyndir/masterpassword/MasterKeyV0.java#L36

It's essentially a SHA-256 hash of the master key, used primarily for verifying whether the master password was entered correctly.

**Comment by ghost** [comment]
@lhunath So if the Java app is not throwing an error, does it not check the Key ID like the iOS app?
@ttyridal I'm mobile at the moment and can't look through your code to see why Key ID is blank.

**Comment by ttyridal** [comment]
the keyid is blank because I've ignored it.  seem like I'll have to add some code to service IOS version then.

**Comment by ttyridal** [comment]
hmm. looking through the IOS code it seems the KeyID field is not actually /needed/, it just doesn't match the pattern `Key ID:<space><zero-or-more-data>`. The string the plugin produces is just `Key ID:`, ie no space. Actually my brief look suggest that it's also ok to just drop the Key ID line completely.

@lhunath do you consider the Key ID to be mandatory in mpsites? is it acceptable to provide a blank Key ID (or no Key ID line at all)?

edit: stuff in brackets wasn't displaying.

**Comment by lhunath** [comment]
I highly recommend that you include the Key ID.  Not including it would be lazy and has a bunch of downsides with no upsides.
1. It's good to have a strong link between a list of passwords and the user identity they belong to, for validation, authenticity and other checks.
2. It is important that there is a check on whether the correct master password was entered.  Without this, an typo in the master password entry will yield no errors, the app will generate passwords for new sites, but they will all be wrong.  When the user logs in with the right key later, he'll be in trouble.
3. The key ID is also useful for the scenario where a user has changed their master password and is importing an older export file, iOS detects this condition, and asks the user for both the old and the new master password so that it can perform migration of any old encrypted passwords in the file to the new master password encryption key.

But yes, you can omit the line.  If you include it, put the valid key ID in it.

**Comment by ttyridal** [comment]
Aren't all software developers lazy ? :)

Thanks.. I'll probably just remove it for this release and plan for adding a correct key Id for the next version then.

**Comment by lhunath** [comment]
hex( sha256( masterKey ) ) is pretty easy :-)  I think anyway, I have no real idea of what libraries / API's you work with.

**Comment by ttyridal** [comment]
@lhunath  Is that hex(sha256( **utf8** ( masterPassword ))) ? (browser-js strings are UTF-16LE)

**Comment by lhunath** [comment]
No, the masterPassword in this case is a byte array, not a string :-)

**Comment by lhunath** [comment]
I should've said, masterKey.

**Comment by ghost** [comment]
I just tested RC2 and it's fixed for me.
