### ISSUE TITLE
Importing creates (visual) duplicates

### ISSUE THREAD

**Issue by ghost** [ttyridal/masterpassword-firefox#25]
If you import a mpsites file while entries already exist then duplicate entries are created.  Maybe the user should be prompted which entry to keep for each site  and then discard the other one.

**Comment by ttyridal** [comment]
As long as the match string is not modified on existing entry (ie matches sitename) it will actually not create a duplicate. It will look that way, since it's appended in the gui, but on storage the existing entry is overwritten (without any warnings)

So if you close and re-open the config window you'll not have duplicates.

Now, silent overwrite is probably not a desired behaviour...

**Comment by ttyridal** [comment]
fix committed and beta software released
