### ISSUE TITLE
window closes immediately

### ISSUE THREAD

**Issue by tibaultbordeaux** [ttyridal/masterpassword-firefox#57]
Hi there!

Thanks for your great addon. Please keep it alive!

Since a few days the window - where i can enter my password - closes immediately after opening.
The add-on is not usable right now for me.

Any hints?

Tibault Bordeaux

**Comment by ttyridal** [comment]
Thanks!

Do you have some more details for me? I assume you mean the first view where you can enter your user name and master password?
Which Firefox version is it you're having trouble with and what operating system?

What happened a few days ago? did you upgrade firefox or something similar?

Cheers

**Comment by tibaultbordeaux** [comment]
Yes, I'm talking about the first view for entering my details.
Firefox 59.0.2
Ubuntu 18.04 LTS

I'm not quite sure, but could be that the error appeared since upgrading from Ubuntu 16.04 to 18.04.

**Comment by ttyridal** [comment]
Hi. Could you help me trying out a couple of things?

First off: What's written to the browser console (Ctrl-Shift-J) when you click the MasterPassword button?

Does it work with a clean profile? You can get one easily with
```
mkdir /tmp/myprofile
firefox -profile /tmp/myprofile
```
Install fresh copy of mpw to the temporary profile.


In your Firefox profile folder (something like`~/.mozilla/firefox/<profile folder>/browser-extension-data/jid1-pn4A...` there should be a file named `storage.js`.  This is all your mpw settings. Could you try to move that file away (when Firefox is closed) 

Does it work if copied and used from the temporary profile?

**Comment by tibaultbordeaux** [comment]
browser console:
`
[CanvasBlocker] invalid content scripts: require not defined  e269a272-5aab-4333-9a9b-ce1d8eedf487:13:9
	<anonym> blob:moz-extension://5b1ba83c-22c2-4854-9c36-7b7442e5a260/e269a272-5aab-4333-9a9b-ce1d8eedf487:13:9
	<anonym> blob:moz-extension://5b1ba83c-22c2-4854-9c36-7b7442e5a260/e269a272-5aab-4333-9a9b-ce1d8eedf487:1:2
pre-main prep time: 1 ms  scrypt-asm.js:1:777
Successfully compiled asm.js code (total compilation time 18ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'))  scrypt-asm.js
`

**Comment by tibaultbordeaux** [comment]
Answer to both questions: No.

The window just stays a bit longer ...
But when clicking into the input field for password -- it disapears like before.

**Comment by Hasimir0** [comment]
In the past few weeks I have been experiencing the same problem.
Running Firefox Beta 61.0b6 (64-bit) on a Ubuntu 18.04 machine.

The app works flawlessly in Chrome Unstable 68.0.3432.3 (64-bit).

Funny thing... I abandoned Chrome in January 2018 specifically because the MasterPasswordApp was not working properly on it :P

**Comment by wi24rd** [comment]
It happened same on my one notebook (i7-6700hq Nvidia 960m, Firefox 59-61) which now is runing Fedora 28. This computer runs Ubuntu 18.04 from March to April (when runing Firefox 59-nightly), which sometimes works, but more frequently can't input password.
Interesting in my another notebook (i5 3320m) which is runing perfectly on Manjaro and Fedora.

**Comment by bettyvschmartz** [comment]
I have the same issue on Firefox 61.0. It only started happening for me since upgrading to Ubuntu 18.04. 

Initially the login drop-down menu would flash on and off immediately, however reinstalling it allowed the window to remain but as soon as I try and navigate to the password field it loses focus again.

Error message in the console is:

`msg.target.ownerGlobal.gBrowser.getTabForBrowser(...) is undefined LoginManagerParent.jsm:134
receiveMessage
resource://gre/modules/LoginManagerParent.jsm:134:25
receiveMessage
jar:file:///usr/lib/firefox/browser/omni.ja!/components/nsBrowserGlue.js:258:15
receiveMessage self-hosted:1028:17`

dll

**Comment by ttyridal** [comment]
Finally got around to have a look at this. Seems to be a ~~Gnome + Firefox~~ GTK3 bug

Someone over here https://bugzilla.mozilla.org/show_bug.cgi?id=1405634#c16 have created a replacement `ibus-gtk3` package that corrects the issue.

other references:

https://bugzilla.mozilla.org/show_bug.cgi?id=1451418#c4

https://bugzilla.mozilla.org/show_bug.cgi?id=1451466

Lot's of other addons have the same problem.

A couple of workarounds are mentioned here:
https://github.com/bitwarden/browser/issues/580

**Comment by bettyvschmartz** [comment]
I can confirm one of these workarounds as working, for me at least. See here:

https://github.com/ibus/ibus/issues/2002#issuecomment-394086168

dll
